export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'

export const USER_SIGN_IN_SHOPIFY_RESPONSE_REQUEST = 'USER_SIGN_IN_SHOPIFY_RESPONSE_REQUEST'
export const USER_SIGN_IN_SHOPIFY_RESPONSE_FAILURE = 'USER_SIGN_IN_SHOPIFY_RESPONSE_FAILURE'
export const USER_SIGN_IN_SHOPIFY_RESPONSE_SUCCESS = 'USER_SIGN_IN_SHOPIFY_RESPONSE_SUCCESS'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST'
export const USER_SESSION_FAILURE = 'USER_SESSION_FAILURE'
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS'

export const CLEAN_UP_STATE_REQUEST = 'CLEAN_UP_STATE_REQUEST'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST'
export const SET_PASSWORD_FAILURE = 'SET_PASSWORD_FAILURE'
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS'

export const USER_SIGN_OUT_REQUEST = 'USER_SIGN_OUT_REQUEST'
export const USER_SIGN_OUT_FAILURE = 'USER_SIGN_OUT_FAILURE'
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS'

export const FORGOT_SEND_OTP_REQUEST = 'FORGOT_SEND_OTP_REQUEST'
export const FORGOT_SEND_OTP_FAILURE = 'FORGOT_SEND_OTP_FAILURE'
export const FORGOT_SEND_OTP_SUCCESS = 'FORGOT_SEND_OTP_SUCCESS'

export const FORGOT_VERIFY_OTP_REQUEST = 'FORGOT_VERIFY_OTP_REQUEST'
export const FORGOT_VERIFY_OTP_FAILURE = 'FORGOT_VERIFY_OTP_FAILURE'
export const FORGOT_VERIFY_OTP_SUCCESS = 'FORGOT_VERIFY_OTP_SUCCESS'

export const REGISTER_VERIFY_OTP_REQUEST = 'REGISTER_VERIFY_OTP_REQUEST'
export const REGISTER_VERIFY_OTP_FAILURE = 'REGISTER_VERIFY_OTP_FAILURE'
export const REGISTER_VERIFY_OTP_SUCCESS = 'REGISTER_VERIFY_OTP_SUCCESS'

export const FORGOT_CHANGE_PASSWORD_REQUEST = 'FORGOT_CHANGE_PASSWORD_REQUEST'
export const FORGOT_CHANGE_PASSWORD_FAILURE = 'FORGOT_CHANGE_PASSWORD_FAILURE'
export const FORGOT_CHANGE_PASSWORD_SUCCESS = 'FORGOT_CHANGE_PASSWORD_SUCCESS'

export const REGISTER_RESEND_OTP_REQUEST = 'REGISTER_RESEND_OTP_REQUEST'
export const REGISTER_RESEND_OTP_FAILURE = 'REGISTER_RESEND_OTP_FAILURE'
export const REGISTER_RESEND_OTP_SUCCESS = 'REGISTER_RESEND_OTP_SUCCESS'
