export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST'
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'

export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST'
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'

export const CLEAN_UP_COMPANY_STATE_REQUEST = 'CLEAN_UP_COMPANY_STATE_REQUEST'
