export const MEDIA_LIST_REQUEST = 'MEDIA_LIST_REQUEST'
export const MEDIA_LIST_FAILURE = 'MEDIA_LIST_FAILURE'
export const MEDIA_LIST_SUCCESS = 'MEDIA_LIST_SUCCESS'

export const ADD_MEDIA_REQUEST = 'ADD_MEDIA_REQUEST'
export const ADD_MEDIA_FAILURE = 'ADD_MEDIA_FAILURE'
export const ADD_MEDIA_SUCCESS = 'ADD_MEDIA_SUCCESS'

export const DELETE_MEDIA_REQUEST = 'DELETE_MEDIA_REQUEST'
export const DELETE_MEDIA_FAILURE = 'DELETE_MEDIA_FAILURE'
export const DELETE_MEDIA_SUCCESS = 'DELETE_MEDIA_SUCCESS'

export const CLEANUP_MEDIA_DATA = 'CLEANUP_MEDIA_DATA'
