export const GET_SUBSCRIPTION_REQUEST = 'GET_SUBSCRIPTION_REQUEST'
export const GET_SUBSCRIPTION_FAILURE = 'GET_SUBSCRIPTION_FAILURE'
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS'

